language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - pytest
services:
  - postgresql
before_script:
  - psql -c 'CREATE database stockarchivedb;' -U postgres
  - psql -c 'CREATE USER stockarchivedb;' -U postgres
