ALTER TABLE yf_stock_daily ALTER COLUMN open TYPE NUMERIC(17,4);
ALTER TABLE yf_stock_daily ALTER COLUMN high TYPE NUMERIC(17,4);
ALTER TABLE yf_stock_daily ALTER COLUMN low TYPE NUMERIC(17,4);
ALTER TABLE yf_stock_daily ALTER COLUMN close TYPE NUMERIC(17,4);

ALTER TABLE yf_stock_intraday ALTER COLUMN open TYPE NUMERIC(17,4);
ALTER TABLE yf_stock_intraday ALTER COLUMN high TYPE NUMERIC(17,4);
ALTER TABLE yf_stock_intraday ALTER COLUMN low TYPE NUMERIC(17,4);
ALTER TABLE yf_stock_intraday ALTER COLUMN close TYPE NUMERIC(17,4);

ALTER TABLE yf_option ALTER COLUMN underlying_bid TYPE NUMERIC(17,4);
ALTER TABLE yf_option ALTER COLUMN underlying_ask TYPE NUMERIC(17,4);

ALTER TABLE fv_stock_daily ALTER COLUMN marketcap TYPE NUMERIC(21,4);
ALTER TABLE fv_stock_daily ALTER COLUMN pe TYPE NUMERIC(17,4);
ALTER TABLE fv_stock_daily ALTER COLUMN price TYPE NUMERIC(17,2);
ALTER TABLE fv_stock_daily ALTER COLUMN change TYPE NUMERIC(17,2);
